name: blog_app
description: "A new Flutter project."
publish_to: "none"

# App version
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Widgets
  cupertino_icons: ^1.0.6
  dotted_border: ^2.1.0


  # State Management & DI
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7

  # Backend & Utils
  supabase_flutter: ^2.3.4
  fpdart: ^1.1.0
  uuid: ^4.3.3
  intl: ^0.19.0
  internet_connection_checker_plus: ^2.2.0
  path_provider: ^2.1.0

  # Local Storage
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13

  # Media
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

# App icon configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo/app_name_text.png
